### ISSUE TITLE
Define LED Limitations

### ISSUE THREAD

**Issue by houseofbugs** [hyperion-project/hyperion.docs#11]
I've spent many nights trying to figure out why my Hyperion setup was not working correctly. The issue ended up being because of my large LED setup (646 LEDs) not working over WLED or even the UDP data options. Couldn't figure out why it wasn't working until checking the max limit of LEDs was searched online.

**Warn the users**
Having a simple error or warning message pop up when using a UDP (or wled) integration would be a HUGE help to prevent people from wasting countless hours trying to figure out why their setup is not working. I am sure you could add some evaluation of the data field when you enter in the LED count to alert the user that they are exceeding the 490 LED limit and propose a workaround (see below). This is not something that is well documented in the Hyperion docs and I almost gave up on this project because of it.

After doing some searched the[ WLED creator stated that 490 is the "hard limit"](https://wled.discourse.group/t/hyperion-max-led-count/180) due to the UDP frame sizes. I spent so much wasted time trying to figure this out.

**Workarounds**

1. Setup 2 WLED instances that each have under that 490 limit and setup multiple LED configurations in Hyperion. Example would be to have the top and right side of your screen on one and the bottom and left side on the other.
2. Use the TPM2.NET integration but this requires calculating the optimal datapacket size to stay within the UDP packet limitations.  This is discussed here; https://wled.discourse.group/t/hyperion-udpraw-to-wled-more-then-490-leds/1258

**Comment by Paulchen-Panther** [comment]
I think this should be done.
https://github.com/hyperion-project/hyperion.ng/pull/1334
