### ISSUE TITLE
ssh access has changed for raspberry pi lite

### ISSUE THREAD

**Issue by laytll** [hyperion-project/hyperion.docs#15]
as per https://www.raspberrypi.com/news/raspberry-pi-bullseye-update-april-2022/ the default user/password is no longer valid, it did not work for me. 

After I do this "Headless setup" I can log in with ssh as normal. 

Also some useful additions to configure ssh and wifi access point credentials all within the tool.

Suggest update to the documentation.

**Comment by tpmodding** [comment]
is now in the latest hyperbian image and also added to the docu thanks to @Lord-Grey
